version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image:
- Visual Studio 2017
- Previous Visual Studio 2017
configuration:
- Debug
- Mixed
- Release
platform:
- x64
- x86
before_build:
- cmd: git submodule update --init --recursive
build:
  project: src/engine.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: xr_pack_build.cmd
test: off
artifacts:
- path: res/OpenXRay.Dx86.7z
  name: OpenXRay.Dx86.7z
- path: res/OpenXRay.Dx64.7z
  name: OpenXRay.Dx64.7z
- path: res/OpenXRay.Mx86.7z
  name: OpenXRay.Mx86.7z
- path: res/OpenXRay.Mx64.7z
  name: OpenXRay.Mx64.7z
- path: res/OpenXRay.Rx86.7z
  name: OpenXRay.Rx86.7z
- path: res/OpenXRay.Rx64.7z
  name: OpenXRay.Rx64.7z
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: OpenXRay (build $(appveyor_build_version))
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: insert_token_here
  artifact: OpenXRay.Dx86.7z, OpenXRay.Dx64.7z, OpenXRay.Mx86.7z, OpenXRay.Mx64.7z, OpenXRay.Rx86.7z, OpenXRay.Rx64.7z
  draft: true
  force_update: true